name: CI Storage
description: "Quickly stores huge work directory with low percentage of changed files on a remote host, or loads it from that host."
branding:
  icon: upload-cloud
  color: blue
inputs:
  action:
    description: "What to do (store or load)."
    required: true
  storage-host:
    description: "Storage host in the format [user@]host[:port]; it must allow password-free SSH key based access. If not passed, tries to read it from ~/ci-storage-host file."
    required: false
  storage-dir:
    description: "Storage directory on the remote host. If not set, uses ~/ci-storage. Notice that owner and repo are always appended, so the final directory will be {storage-dir}/{owner}/{repo} or {storage-dir}/{owner}/{repo}.{storage-namespace}."
    required: false
  storage-max-age-sec:
    description: "Remove slots created earlier than this many seconds ago. If not set, uses the ci-storage tool default 4 hours."
    required: false
  slot-id:
    description: 'Id of the slot to store to or load from; use "*" to load a random most recent slot and skip if it does not exist. If empty, uses "$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT" value.'
    required: false
  local-dir:
    description: 'Local directory path to store from or load to. If not set, uses "." (the current work directory).'
    required: false
  exclude:
    description: "Newline separated exclude pattern(s) for rsync."
    required: false
  layer-name:
    description: "If set, the final directory on the storage host will be {storage-dir}/{owner}/{repo}.{layer-name}, plus deletion will be turned off on load."
    required: false
  layer-include:
    description: "Newline-separated include pattern(s) for rsync. If set, only the files matching the patterns will be transferred. Implies setting layer-name."
    required: false
  verbose:
    description: "If set, prints the list of transferred files."
    required: false
runs:
  using: "composite"
  steps:
    - name: Run ci-storage ${{ inputs.action }}
      run: |
        exec 2>&1; set -e -o xtrace
        pwd
        storage_host="${{ inputs.storage-host || '' }}"
        if [[ "$storage_host" == "" ]]; then
          storage_host=$(cat ~/ci-storage-host)
        fi
        storage_dir="${{ inputs.storage-dir || '~/ci-storage' }}/${{ github.repository }}"
        layer_name="${{ inputs.layer-name || '' }}"
        layer_include="${{ inputs.layer-include || '' }}"
        if [[ "$layer_name" != "" ]]; then
          layer_include=${layer_include:-"*"}
          storage_dir="$storage_dir.$layer_name"
        fi
        if [[ "$layer_include" != "" && "$layer_name" == "" ]]; then
          echo "When layer-include is used, you must also pass layer-name."
          exit 1
        fi
        "${{ github.action_path }}/ci-storage" \
          --storage-host="$storage_host" \
          --storage-dir="$storage_dir" \
          --storage-max-age-sec="${{ inputs.storage-max-age-sec || '' }}" \
          --slot-id="${{ inputs.slot-id || format('{0}-{1}', github.run_id, github.run_attempt) }}" \
          --local-dir="${{ inputs.local-dir || '.' }}" \
          --exclude="${{ inputs.exclude || '' }}" \
          --layer="$layer_include" \
          ${{ inputs.verbose && '--verbose' || '' }} \
          ${{ inputs.action }}
      shell: bash
