name: CI Storage
description: "Quickly stores huge work directory with low percentage of changed files on a remote host, or loads it from that host."
branding:
  icon: upload-cloud
  color: blue
inputs:
  action:
    description: "What to do (store or load)."
    required: true
  storage-host:
    description: "Storage host in the format [user@]host[:port]; it must allow password-free SSH key based access. If not passed, tries to read it from ~/ci-storage-host file."
    required: false
  storage-dir:
    description: "Storage directory on the remote host. If not set, uses /mnt. Notice that owner and repo are always appended, so the final directory will be {storage-dir}/{owner}/{repo} or {storage-dir}/{owner}/{repo}.{storage-namespace}."
    required: false
  storage-max-age-sec:
    description: "Remove slots created earlier than this many seconds ago. If not set, uses the ci-storage tool default 4 hours."
    required: false
  slot-id:
    description: 'Id of the slot to store to or load from; use "*" to load a smart-random slot (e.g. most recent or best in terms of layer compatibility) and skip if it does not exist. If empty, uses $GITHUB_RUN_ID value (which is friendly to "Re-run failed jobs").'
    required: false
  local-dir:
    description: 'Local directory path to store from or load to. If not set, uses "." (the current work directory).'
    required: false
  exclude:
    description: "Newline separated exclude pattern(s) for rsync."
    required: false
  layer-name:
    description: "If set, the final directory on the storage host will be {storage-dir}/{owner}/{repo}.{layer-name}, plus deletion will be turned off on load."
    required: false
  layer-include:
    description: "Newline-separated include pattern(s) for rsync. If set, only the files matching the patterns will be transferred. Implies setting layer-name."
    required: false
  verbose:
    description: "If set, prints the list of transferred files."
    required: false
runs:
  using: "composite"
  steps:
    - name: Run ci-storage ${{ inputs.action }}
      shell: bash
      run: |
        exec 2>&1; set -e -o xtrace
        pwd
        date

        default_run_hash="${{ github.run_id }}"

        action="${{ inputs.action }}"
        storage_host="${{ inputs.storage-host || '' }}"
        storage_dir="${{ inputs.storage-dir || '/mnt' }}/${{ github.repository }}"
        storage_max_age_sec="${{ inputs.storage-max-age-sec || '' }}"
        slot_id="${{ inputs.slot-id }}"
        local_dir="${{ inputs.local-dir || '.' }}"
        exclude="${{ inputs.exclude || '' }}"
        layer_name="${{ inputs.layer-name || '' }}"
        layer_include="${{ inputs.layer-include || '' }}"
        verbose="${{ inputs.verbose && '--verbose' || '' }}"

        if [[ "$storage_host" == "" ]]; then
          storage_host=$(cat ~/ci-storage-host)
        fi

        if [[ "$slot_id" == "" ]]; then
          slot_id="$default_run_hash"
        elif [[ "$slot_id" == "*" && "$action" == "load" ]]; then
          # If "*" is used, always prefer our own default_run_hash.
          slot_id="$default_run_hash $slot_id"
        fi

        if [[ "$layer_name" != "" ]]; then
          layer_include=${layer_include:-"*"}
          storage_dir="$storage_dir.$layer_name"
        fi
        if [[ "$layer_include" != "" && "$layer_name" == "" ]]; then
          echo "When layer-include is used, you must also pass layer-name."
          exit 1
        fi

        "${{ github.action_path }}/ci-storage" \
          --storage-host="$storage_host" \
          --storage-dir="$storage_dir" \
          --storage-max-age-sec="$storage_max_age_sec" \
          --slot-id="$slot_id" \
          --local-dir="$local_dir" \
          --exclude="$exclude" \
          --layer="$layer_include" \
          $verbose \
          "$action"
