version: "3.4"
services:
  host:
    build:
      context: host
      dockerfile: Dockerfile
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD", "bash", "-c", "netstat -ltn | grep -c :22"]
      interval: 1s
      timeout: 3s
      retries: 10
    ports:
      - 10022:22
    secrets:
      - CI_STORAGE_PUBLIC_KEY
  self-hosted-runner:
    build:
      context: self-hosted-runner
      dockerfile: Dockerfile
    stop_grace_period: 1m
    depends_on:
      host:
        condition: service_healthy
    environment:
      - GH_REPOSITORY=${GH_REPOSITORY:-dimikot/ci-storage}
      - GH_LABELS=${GH_LABELS:-ci-storage}
      - GH_TOKEN
      - FORWARD_HOST=
      - FORWARD_PORTS=22/tcp
      - CI_STORAGE_HOST=${CI_STORAGE_HOST:-host:22}
    secrets:
      - CI_STORAGE_PRIVATE_KEY
secrets:
  CI_STORAGE_PUBLIC_KEY:
    file: ./test-public-key
  CI_STORAGE_PRIVATE_KEY:
    file: ./test-private-key
