services:
  ci-storage:
    build:
      context: ci-storage
      dockerfile: Dockerfile
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD", "bash", "-c", "netstat -ltn | grep -c :22"]
      interval: 1s
      timeout: 3s
      retries: 10
    ports:
      - 10022:22
    environment:
      - TZ=${TZ:-}
    secrets:
      - CI_STORAGE_PUBLIC_KEY
    volumes:
      - ${CI_STORAGE_MNT_VOLUME:-ci-storage-mnt}:/mnt
  ci-runner:
    build:
      context: ci-runner
      dockerfile: Dockerfile
    stop_grace_period: 1m
    depends_on:
      ci-storage:
        condition: service_healthy
    environment:
      - GH_TOKEN
      - GH_REPOSITORY=${GH_REPOSITORY:-dimikot/ci-storage}
      - GH_LABELS=${GH_LABELS:-ci-storage}
      - FORWARD_HOST=${FORWARD_HOST:-}
      - FORWARD_PORTS=${FORWARD_PORT:-22/tcp 8125/udp}
      - CI_STORAGE_HOST=${CI_STORAGE_HOST:-ci-storage:22}
      - TZ=${TZ:-}
      - DEBUG_SHUTDOWN_DELAY_SEC=${DEBUG_SHUTDOWN_DELAY_SEC:-1}
    secrets:
      - CI_STORAGE_PRIVATE_KEY
    tmpfs:
      - /mnt:exec
secrets:
  CI_STORAGE_PUBLIC_KEY:
    file: ./test-public-key
  CI_STORAGE_PRIVATE_KEY:
    file: ./test-private-key
volumes:
  ci-storage-mnt:
    external: false
