#
# This compose.yml file is used for local testing. You can also use it as a
# template for your own deployment. See also README.md files with more examples.
#

services:
  ci-scaler:
    build:
      context: ci-scaler
      dockerfile: Dockerfile
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD", "bash", "-c", "netstat -ltn | grep -c :8088"]
      interval: 1s
      timeout: 3s
      retries: 10
    ports:
      - 18088:8088
    environment:
      - GH_TOKEN
      - ASGS
      - DOMAIN
      - TZ

  ci-storage:
    build:
      context: ci-storage
      dockerfile: Dockerfile
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD", "bash", "-c", "netstat -ltn | grep -c :22"]
      interval: 1s
      timeout: 3s
      retries: 10
    ports:
      - 10022:22
    environment:
      - TZ
    volumes:
      - ci-storage-mnt:/mnt
    secrets:
      - CI_STORAGE_PUBLIC_KEY

  ci-runner:
    build:
      context: ci-runner
      dockerfile: Dockerfile
    stop_grace_period: 1m
    depends_on:
      ci-storage:
        condition: service_healthy
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - GH_TOKEN
      - GH_REPOSITORY
      - GH_LABELS
      - TZ
      - FORWARD_HOST
      - FORWARD_PORTS=10022/tcp 8125/udp
      - CI_STORAGE_HOST=127.0.0.1:10022
      - DEBUG_SHUTDOWN_DELAY_SEC=1
    secrets:
      - CI_STORAGE_PRIVATE_KEY
    tmpfs:
      - /mnt:exec

volumes:
  ci-storage-mnt:
    external: false

secrets:
  CI_STORAGE_PUBLIC_KEY:
    file: ./test-public-key
  CI_STORAGE_PRIVATE_KEY:
    file: ./test-private-key
