version: "3.4"
services:
  host:
    build:
      context: host
      dockerfile: Dockerfile
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD", "bash", "-c", "netstat -ltn | grep -c :22"]
      interval: 1s
      timeout: 3s
      retries: 10
    ports:
      - 10022:22
    environment:
      - CI_STORAGE_HOST_PUBLIC_KEY_EVAL=${CI_STORAGE_HOST_PUBLIC_KEY_EVAL_TEST_ONLY?}
  self-hosted-runner:
    build:
      context: self-hosted-runner
      dockerfile: Dockerfile
    stop_grace_period: 1m
    depends_on:
      host:
        condition: service_healthy
    environment:
      - GH_REPOSITORY=${GH_REPOSITORY:-dimikot/ci-storage}
      - GH_LABELS=${GH_LABELS:-ci-storage}
      - GH_TOKEN
      - CI_STORAGE_HOST=${CI_STORAGE_HOST:-host:22}
      - CI_STORAGE_HOST_PRIVATE_KEY_EVAL=${CI_STORAGE_HOST_PRIVATE_KEY_EVAL_TEST_ONLY?}
