version: "3.4"
services:
  ci-storage-host:
    build:
      context: ci-storage-host
      dockerfile: Dockerfile
    ports:
      - 10022:22
    environment:
      - GH_REPOSITORY
      - CI_STORAGE_HOST_SSH_KEY
  self-hosted-runner:
    build:
      context: self-hosted-runner
      additional_contexts:
        root: ..
      dockerfile: Dockerfile
    environment:
      - GH_REPOSITORY
      - GH_LABELS
      - GH_TOKEN
      - CI_STORAGE_HOST=ci-storage-host
      - CI_STORAGE_HOST_SSH_KEY
